name: Trigger Daily Cloudflare Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages Build
        run: curl -X POST "${{ secrets.CLOUDFLARE_BUILD_HOOK_URL }}"
